[package]
name = "wasm-hbc"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
hblang = { workspace = true, features = [] }
hbvm.workspace = true
log = "0.4.22"
wasm-rt = { version = "0.1.0", path = "../wasm-rt", features = ["log"] }

