[package]
name = "hbasm"
version = "0.1.0"
edition = "2021"

[dependencies]
hbbytecode = { path = "../hbbytecode" }
lasso      = "0.7"
paste      = "1.0"

[dependencies.logos]
version = "0.13"
default-features = false
features = ["export_derive"]
