[package]
name = "hbasm"
version = "0.1.0"
edition = "2021"

[dependencies]
paste               = "1.0"
with_builtin_macros = "0.0.3"

[dependencies.mlua]
version  = "0.9"
features = ["luajit52", "macros", "vendored"]
