[package]
name = "hblang"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "hbc"
path = "src/main.rs"

[dependencies]
env_logger = "0.11.5"
hbvm = { path = "../hbvm", features = ["nightly"] }
log = "0.4.22"
regalloc2 = { version = "0.10.2", features = ["trace-log"] }
