[package]
name = "wasm-hbfmt"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
hblang = { version = "0.1.0", path = "../../hblang", default-features = false, features = ["no_log"] }
