[package]
name = "hbvm"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = true

[dependencies]
delegate          = "0.9"
derive_more       = "0.99"
hashbrown         = "0.13"
hbbytecode.path   = "../hbbytecode"
log               = "0.4"
paste             = "1.0"
static_assertions = "1.0"
